CREATE TABLE likes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    liker_id   BIGINT                                  NOT NULL,
    liked_id   BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_likes PRIMARY KEY (id)
);

ALTER TABLE likes
    ADD CONSTRAINT uc_likes_liker_id_liked_id UNIQUE (liker_id, liked_id);