CREATE TABLE likes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    liker_id   BIGINT                                  NOT NULL,
    liked_id   BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_likes PRIMARY KEY (id)
);

CREATE TABLE blocks
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    blocker_id BIGINT                                  NOT NULL,
    blocked_id BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_blocks PRIMARY KEY (id)
);

ALTER TABLE likes
    ADD CONSTRAINT uc_likes_liker_id_liked_id UNIQUE (liker_id, liked_id);

ALTER TABLE blocks
    ADD CONSTRAINT uc_blocks_blocker_id_blocked_id UNIQUE (blocker_id, blocked_id);