CREATE TABLE point
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_id  BIGINT                                  NOT NULL,
    balance    BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_point PRIMARY KEY (id)
);

CREATE TABLE point_transaction
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_id        BIGINT                                  NOT NULL,
    type             VARCHAR(255)                            NOT NULL,
    source           VARCHAR(255)                            NOT NULL,
    amount           BIGINT                                  NOT NULL,
    balance_snapshot BIGINT                                  NOT NULL,
    description      VARCHAR(255),
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_point_transaction PRIMARY KEY (id)
);

CREATE TABLE likes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    liker_id   BIGINT                                  NOT NULL,
    liked_id   BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_likes PRIMARY KEY (id)
);

CREATE TABLE private_image_grants
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    granter_id BIGINT                                  NOT NULL,
    grantee_id BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_private_image_grants PRIMARY KEY (id)
);

CREATE TABLE blocks
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    blocker_id BIGINT                                  NOT NULL,
    blocked_id BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_blocks PRIMARY KEY (id)
);

CREATE TABLE report
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reporter_id           BIGINT                                  NOT NULL,
    reporter_uuid         VARCHAR(255)                            NOT NULL,
    reporter_phone_number VARCHAR(255)                            NOT NULL,
    reporter_nickname     VARCHAR(255)                            NOT NULL,
    reported_id           BIGINT                                  NOT NULL,
    reported_uuid         VARCHAR(255)                            NOT NULL,
    reported_phone_number VARCHAR(255)                            NOT NULL,
    reported_nickname     VARCHAR(255)                            NOT NULL,
    status                VARCHAR(255)                            NOT NULL,
    type                  VARCHAR(255)                            NOT NULL,
    reason                TEXT,
    created_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_report PRIMARY KEY (id)
);

CREATE TABLE report_image
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    report_id  BIGINT                                  NOT NULL,
    key        VARCHAR(255)                            NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    sort_order INTEGER                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_report_image PRIMARY KEY (id)
);

ALTER TABLE point
    ADD CONSTRAINT uc_point_member UNIQUE (member_id);

ALTER TABLE likes
    ADD CONSTRAINT uc_likes_liker_id_liked_id UNIQUE (liker_id, liked_id);

ALTER TABLE private_image_grants
    ADD CONSTRAINT uc_private_image_grants_granter_id_grantee_id UNIQUE (granter_id, grantee_id);

ALTER TABLE blocks
    ADD CONSTRAINT uc_blocks_blocker_id_blocked_id UNIQUE (blocker_id, blocked_id);