CREATE TABLE member
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid            VARCHAR(255)                            NOT NULL,
    phone_number    VARCHAR(255)                            NOT NULL,
    nickname        VARCHAR(255)                            NOT NULL,
    password        VARCHAR(255)                            NOT NULL,
    gender          VARCHAR(255)                            NOT NULL,
    profile_key     VARCHAR(255),
    birth_year      INTEGER                                 NOT NULL,
    bio             VARCHAR(1000),
    comment         VARCHAR(100),
    location        GEOGRAPHY(Point, 4326),
    is_chat_enabled BOOLEAN,
    role            VARCHAR(255)                            NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_member PRIMARY KEY (id)
);

CREATE TABLE member_image
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_id  BIGINT                                  NOT NULL,
    key        VARCHAR(255)                            NOT NULL,
    type       VARCHAR(255)                            NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    sort_order INTEGER                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_member_image PRIMARY KEY (id)
);

CREATE TABLE point
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_id  BIGINT                                  NOT NULL,
    balance    BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_point PRIMARY KEY (id)
);

CREATE TABLE point_transaction
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_id        BIGINT                                  NOT NULL,
    type             VARCHAR(255)                            NOT NULL,
    source           VARCHAR(255)                            NOT NULL,
    amount           BIGINT                                  NOT NULL,
    balance_snapshot BIGINT                                  NOT NULL,
    description      VARCHAR(255),
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_point_transaction PRIMARY KEY (id)
);

CREATE TABLE chat_room
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member1_id                   BIGINT                                  NOT NULL,
    member2_id                   BIGINT                                  NOT NULL,
    last_message                 VARCHAR(255),
    member1_last_read_message_id BIGINT,
    member2_last_read_message_id BIGINT,
    member1_unread_count         INTEGER,
    member2_unread_count         INTEGER,
    last_message_at              TIMESTAMP WITHOUT TIME ZONE,
    created_at                   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted_at                   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_chat_room PRIMARY KEY (id)
);

CREATE TABLE message
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_room_id BIGINT                                  NOT NULL,
    sender_id    BIGINT                                  NOT NULL,
    content      TEXT                                    NOT NULL,
    type         VARCHAR(255)                            NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_message PRIMARY KEY (id)
);

CREATE TABLE likes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    liker_id   BIGINT                                  NOT NULL,
    liked_id   BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_likes PRIMARY KEY (id)
);

CREATE TABLE private_image_grants
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    granter_id BIGINT                                  NOT NULL,
    grantee_id BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_private_image_grants PRIMARY KEY (id)
);

CREATE TABLE blocks
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    blocker_id BIGINT                                  NOT NULL,
    blocked_id BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_blocks PRIMARY KEY (id)
);

CREATE TABLE report
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reporter_id           BIGINT                                  NOT NULL,
    reporter_uuid         VARCHAR(255)                            NOT NULL,
    reporter_phone_number VARCHAR(255)                            NOT NULL,
    reporter_nickname     VARCHAR(255)                            NOT NULL,
    reported_id           BIGINT                                  NOT NULL,
    reported_uuid         VARCHAR(255)                            NOT NULL,
    reported_phone_number VARCHAR(255)                            NOT NULL,
    reported_nickname     VARCHAR(255)                            NOT NULL,
    status                VARCHAR(255)                            NOT NULL,
    type                  VARCHAR(255)                            NOT NULL,
    reason                TEXT,
    created_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_report PRIMARY KEY (id)
);

CREATE TABLE report_image
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    report_id  BIGINT                                  NOT NULL,
    key        VARCHAR(255)                            NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    sort_order INTEGER                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_report_image PRIMARY KEY (id)
);

CREATE TABLE phone_verification
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    verification_code VARCHAR(255)                            NOT NULL,
    phone_number      VARCHAR(255)                            NOT NULL,
    client_ip         VARCHAR(255)                            NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_phone_verification PRIMARY KEY (id)
);

CREATE UNIQUE INDEX uq_member_phone_active
    ON member (phone_number)
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX uq_member_nickname_active
    ON member (nickname)
    WHERE deleted_at IS NULL;

ALTER TABLE point
    ADD CONSTRAINT uc_point_member UNIQUE (member_id);

CREATE UNIQUE INDEX uq_chat_room_members_active
    ON chat_room (LEAST(member1_id, member2_id), GREATEST(member1_id, member2_id))
    WHERE deleted_at IS NULL;

ALTER TABLE likes
    ADD CONSTRAINT uc_likes_liker_id_liked_id UNIQUE (liker_id, liked_id);

ALTER TABLE private_image_grants
    ADD CONSTRAINT uc_private_image_grants_granter_id_grantee_id UNIQUE (granter_id, grantee_id);

ALTER TABLE blocks
    ADD CONSTRAINT uc_blocks_blocker_id_blocked_id UNIQUE (blocker_id, blocked_id);